routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('resume/create');
});

Route::resource('resume', 'ResumeController');

app/Resume.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Resume extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'job', 'work_at', 'phone', 'email', 'experience'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * Change the date view format.
     *
     * @param  string  $value
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d M Y');
    }

    /**
     * The skill that belong to the resume.
     */
    public function skills()
    {
        return $this->belongsToMany('App\Skill');
    }
}

app/Skill.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The resume that belong to the skill.
     */
    public function resumes()
    {
        return $this->belongsToMany('App\Resume');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ResumeController.php
<?php

namespace App\Http\Controllers;

use App\Resume;
use App\Skill;
use Illuminate\Http\Request;
use Validator;

class ResumeController extends Controller
{

    /**
    * Index view of the resume.
    *
    * @return \Illuminate\Http\Response
    */
    public function index(){

      $resume = Resume::first();

      return view('resume.index', compact('resume'));
    }

    /**
    * View to create new resume.
    *
    * @return \Illuminate\Http\Response
    */
    public function create(){

      $skills = Skill::all();

      return view('resume.create', compact('skills'));
    }

    /**
     * Create a new resume instance.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request){

      $validator = Validator::make($request->all(), [
          'name'        => 'required',
          'job'         => 'required',
          'work_at'     => 'required',
          'phone'       => 'required',
          'email'       => 'required',
          'experience'  => 'required',
          'skill_id'    => 'required'
      ]);

      if ($validator->fails()) {
          return redirect()->back()
                      ->withErrors($validator)
                      ->withInput();
      }

      $resume = new Resume;
      $resume->name        = $request->name;
      $resume->job         = $request->job;
      $resume->work_at     = $request->work_at;
      $resume->phone       = $request->phone;
      $resume->email       = $request->email;
      $resume->experience  = $request->experience;

      if ($resume->save()) {
        $skill_id   = $request->skill_id;
        $attach     = Resume::findOrFail($resume->id);
        $attach->skills()->attach($skill_id);

        return redirect()->route('resume.index');
      }
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name') }}
                </a>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/resume/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Resume Form</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('resume.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-2 col-form-label text-md-right">Full Name</label>

                            <div class="col-md-8">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="job" class="col-md-2 col-form-label text-md-right">Jobs</label>

                            <div class="col-md-8">
                                <input id="job" type="text" class="form-control{{ $errors->has('job') ? ' is-invalid' : '' }}" name="job" value="{{ old('job') }}" required>

                                @if ($errors->has('job'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('job') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="work_at" class="col-md-2 col-form-label text-md-right">Work At</label>

                            <div class="col-md-8">
                                <input id="work_at" type="text" class="form-control{{ $errors->has('work_at') ? ' is-invalid' : '' }}" name="work_at" value="{{ old('work_at') }}" required>

                                @if ($errors->has('work_at'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('work_at') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-2 col-form-label text-md-right">Phone</label>

                            <div class="col-md-8">
                                <input id="phone" type="number" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" value="{{ old('phone') }}" required>

                                @if ($errors->has('phone'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-2 col-form-label text-md-right">Email</label>

                            <div class="col-md-8">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="experience" class="col-md-2 col-form-label text-md-right">Experience</label>

                            <div class="col-md-8">

                                <textarea id="experience" name="experience" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" rows="8" cols="80" required>{{ old('email') }}</textarea>

                                @if ($errors->has('experience'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('experience') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="skill_id[]" class="col-md-2 col-form-label text-md-right">Skills</label>

                            <div class="col-md-8">

                                @foreach ($skills as $skill)
                                  <input id="skill_id[]" type="checkbox" class="{{ $errors->has('skill_id') ? ' is-invalid' : '' }}" name="skill_id[]" value="{{ $skill->id }}"> <span>{{ $skill->name }}</span> <br/>
                                @endforeach

                                @if ($errors->has('skill_id'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('skill_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/resume/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
  <div class="col-md-10">
    <div class="row mb-3 jumbotron">
      <div class="col-md-4">
        <figure class="figure">
            <img src="{{ asset('image/people-m.png') }}" class="figure-img img-fluid rounded-circle" width="150px" alt="Set your avatar">
        </figure>
      </div>
      <div class="col-md-8">
        <ul class="list-group">
            <li class="list-group-item">{{ $resume->name }}</li>
            <li class="list-group-item">{{ $resume->job }}</li>
            <li class="list-group-item">{{ $resume->work_at }}</li>
            <li class="list-group-item">{{ $resume->phone }}</li>
            <li class="list-group-item">{{ $resume->email }}</li>
        </ul>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <blockquote class="blockquote">
              <p class="mb-0">{{ $resume->experience }}</p>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-12">
        <p>Skills</p>
        @foreach ($resume->skills as $skill)
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ $skill->name }}</div>
          </div>
          <br>
        @endforeach
      </div>
    </div>
  </div>
</div>
</div>
@endsection